### PR TITLE
Add updated descriptions for core fields to readme + update changelog

### PR DESCRIPTION
**Pull request by duncandewhurst**
See https://github.com/open-contracting/ocds-extensions/issues/46#issuecomment-383943481

Fixes https://github.com/open-contracting/ocds-extensions/issues/46

### CODE REVIEW

**Comment by jpmckinney** [comment]
Sadly, we must use RST tables, because Sphinx can't compile Markdown tables. I made that commit.

Re-reading the definitions in the readme, they seem to be rewordings without any clear, intentional semantic differences. Can we simply omit this from the readme?

If we think the definitions offer improvements to core, we can create an issue on core.

**Update:** I see it's already created: https://github.com/open-contracting/standard/issues/701

**Comment by duncandewhurst** [comment]
For `planning/budget` the new definition clarifies that the field should be used for the budget **estimated for, or allocated to** the project. I think this was probably an attempt to address issues where some publishers had been using the budget section to represent the total value of the budget line from which the contracting process would be funded.

For `budget/description` the new definition introduces the option of using the field to describe **the nature and source of the allocation (e.g. conditional, confirmed; any official authorizations given to the budget allocation)** in addition to the title of the budget line. I think this was probably an attempt to guide publishers on where to provide information on what stage of the budget cycle the allocation for the project is at.

So I think these definitions add some extra information to the descriptions in the schema, rather than just being rewordings.

As to whether its important to include that extra information in the readme for this extension, let's check with @timgdavies since I think he authored these descriptions originally.

**Comment by jpmckinney** [comment]
Can we replace the readme text with guidance that clearly describes the distinctions / additions / clarifications being made to the core definition? Right now, it is a total substitution, which leaves it up to users to interpret what exactly is different and what is the intention of the new wording compared to the core definition.

**Comment by jpmckinney** [comment]
I'm not sure why "This field should not be used to report the total value of the budget line which funds this contracting process." is added for `planning/budget`, which is an object and thus cannot be used to report a value (but `planning/budget/amount` can).

Similarly, the clarification that the amount could be "the specific budget estimated for, or allocated to, this contracting process" is clearer on `amount` than on the object.

I don't see what `planning/budget/id` contributes to the OCDS description. "formal budget documents" are the most likely "provided data source". At minimum, we should delete "Wherever possible", as the construction "Wherever possible … should be possible" makes no sense.

**Comment by duncandewhurst** [comment]
> I'm not sure why "This field should not be used to report the total value of the budget line which funds this contracting process." is added for planning/budget, which is an object and thus cannot be used to report a value (but planning/budget/amount can).
>
> Similarly, the clarification that the amount could be "the specific budget estimated for, or allocated to, this contracting process" is clearer on amount than on the object.

The guidance in the readme was added to `planning/budget` since this was the property it came from in the extension schema, but I agree these do make more sense on `budget/amount` so I've moved them there.

> I don't see what planning/budget/id contributes to the OCDS description. "formal budget documents" are the most likely "provided data source". At minimum, we should delete "Wherever possible", as the construction "Wherever possible … should be possible" makes no sense.

`budget/source` was deprecated in OCDS 1.1, so I think this was an attempt to move the language away from the terminology of "data source". I've removed "wherever possible".

**Comment by jpmckinney** [comment]
@duncandewhurst I made some small edits. Feel free to merge.

**Pull request merged**
